export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED ="USER_REGISTER_FAILED"

export const USER_VERIFY_REQUEST = "USER_VERIFY_REQUEST"
export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS"
export const USER_VERIFY_FAILED = "USER_VERIFY_FAILED"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const USER_LOGIN_VERIFY_REQUEST = "USER_LOGIN_VERIFY_REQUEST"
export const USER_LOGIN_VERIFY_SUCCESS = "USER_LOGIN_VERIFY_SUCCESS"
export const USER_LOGIN_VERIFY_FAILED = "USER_LOGIN_VERIFY_FAILED"

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED"

export const USER_REFRESH = "USER_REFRESH"